### ISSUE TITLE
Field definitions - lad_attributes.csv

### ISSUE THREAD

**Issue by nujcharee** [npct/pct-outputs-national#2]
Hi there,
Thank you for these examples but I am new to pct dataset and wonder if you could advice what each columns mean please? Im grateful for your assistance.

Nujcharee :)

**Comment by nikolai-b** [comment]
Hi,

http://www.pct.bike/
Offers a more user friendly interface to the data. If you select a region i.e.  [Isle of Wight](http://www.pct.bike/m/?r=isle-of-wight) then select the regional (or national data) tab there are links to the data along with codebooks explaining the variables.  Feedback would be greatly appreciated!

**Comment by nikolai-b** [comment]
The from the national data tab here is the [lad codebook](https://cdn.rawgit.com/npct/pct-shiny/master/regions_www/www/static/02_codebooks/commute/lad_codebook.csv)

**Comment by nujcharee** [comment]
That’s useful thank you
